# Generated by Django 4.1.2 on 2022-12-02 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=100)),
                ('contact_hours', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('textbook', models.TextField()),
                ('other_supplementary_material', models.TextField()),
                ('course_description', models.TextField()),
                ('prerequisites', models.CharField(max_length=100)),
                ('corequisites', models.CharField(max_length=100)),
                ('course_classification', models.TextField()),
                ('course_objective', models.TextField()),
                ('course_outcomes', models.TextField()),
                ('student_outcome_addressed_by_the_course', models.TextField()),
                ('course_topics', models.TextField()),
                ('prepared', models.CharField(max_length=100)),
                ('noted', models.CharField(max_length=100)),
                ('marked', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
