# Generated by Django 4.1.2 on 2022-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course_classification',
            field=models.CharField(max_length=100),
        ),
    ]
