# Generated by Django 4.2.3 on 2023-07-24 02:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabook', '0003_alter_post_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_hours',
            field=models.CharField(max_length=100, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='post',
            name='corequisites',
            field=models.CharField(max_length=100, verbose_name='Corequisite'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_classification',
            field=models.CharField(max_length=100, verbose_name='Course classification'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_code',
            field=models.CharField(max_length=100, verbose_name='Course code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_name',
            field=models.CharField(max_length=100, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_objective',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Course objective'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_outcomes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Course outcome'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_topics',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='credits',
            field=models.CharField(max_length=100, verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='post',
            name='instructor',
            field=models.CharField(max_length=100, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='marked',
            field=models.CharField(max_length=100, verbose_name='Signed by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='noted',
            field=models.CharField(max_length=100, verbose_name='Noted by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='other_supplementary_material',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Other materials'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prepared',
            field=models.CharField(max_length=100, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prerequisites',
            field=models.CharField(max_length=100, verbose_name='Prerequisite'),
        ),
        migrations.AlterField(
            model_name='post',
            name='student_outcome_addressed_by_the_course',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Student outcome'),
        ),
        migrations.AlterField(
            model_name='post',
            name='textbook',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text books'),
        ),
    ]
